todo_api_0: clean
	gcc -g -Wall -Wextra -Werror -pedantic -o $@ 4-server.c

todo_api_1: clean
	gcc -g -Wall -Wextra -Werror -pedantic -o $@ 5-server.c

todo_api_2: clean
	gcc -g -Wall -Wextra -Werror -pedantic -o $@ 6-server.c

todo_api_3: clean
	gcc -g -Wall -Wextra -Werror -pedantic -o $@ 7-server.c

clean:
	rm -f todo_api_0 todo_api_1 todo_api_2 todo_api_3